### ISSUE TITLE
doe not work for me

### ISSUE THREAD

**Issue by culurciello** [mykongee/room-editor#4]
sorry to be so general, but this code does not work for me when I run it. Manye issues and error. Am wondering if this is the latest code and if it works for you

**Comment by mykongee** [comment]
Thanks for bringing this up Eugenio! I've pushed an update that fixed the breaking errors. 
It was due to invoked useState() without having it imported from react.
To test out the application, please run the following in the root directory of the project:
`npm i`
`npm run dev`

**Comment by culurciello** [comment]
Yea -- works, thanks a lot! I am new to reactive apps, am learning so was not able to fix the issue. Thanks a lot.
